// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1dNLi-AiJT2CfyYyt8SxMSMkNmIOXLwM',
    appId: '1:1014496627376:web:b301a6c82e1d08bc8f4975',
    messagingSenderId: '1014496627376',
    projectId: 'fir-project-job',
    authDomain: 'fir-project-job.firebaseapp.com',
    storageBucket: 'fir-project-job.appspot.com',
    measurementId: 'G-TRF6VW858T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ouLhSFg7q_xfCMns5cPQVl3ZlExBKwE',
    appId: '1:1014496627376:android:47dd865be0c8ef898f4975',
    messagingSenderId: '1014496627376',
    projectId: 'fir-project-job',
    storageBucket: 'fir-project-job.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDvsv5Lbgg0FwmH-VBG5eXneC3evc30Xs',
    appId: '1:1014496627376:ios:2cd4dddf8eeebbb08f4975',
    messagingSenderId: '1014496627376',
    projectId: 'fir-project-job',
    storageBucket: 'fir-project-job.appspot.com',
    iosClientId: '1014496627376-jcd2op3h2jkthe6knfbdc85ijlebp4gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobSearchAppAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDvsv5Lbgg0FwmH-VBG5eXneC3evc30Xs',
    appId: '1:1014496627376:ios:2cd4dddf8eeebbb08f4975',
    messagingSenderId: '1014496627376',
    projectId: 'fir-project-job',
    storageBucket: 'fir-project-job.appspot.com',
    iosClientId: '1014496627376-jcd2op3h2jkthe6knfbdc85ijlebp4gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobSearchAppAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1dNLi-AiJT2CfyYyt8SxMSMkNmIOXLwM',
    appId: '1:1014496627376:web:d4fc0621ef3bca3f8f4975',
    messagingSenderId: '1014496627376',
    projectId: 'fir-project-job',
    authDomain: 'fir-project-job.firebaseapp.com',
    storageBucket: 'fir-project-job.appspot.com',
    measurementId: 'G-KW8K61CZMY',
  );
}
